# Generated by Django 2.0 on 2018-03-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
    ]
